/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author majdi
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws ParseException, UnsupportedLookAndFeelException {
        initComponents();
        
        Toolkit tool=Toolkit.getDefaultToolkit();
          Dimension dim=new Dimension(tool.getScreenSize());
          int height1=(int)dim.getHeight();
          int width1=(int)dim.getWidth();
          setSize(width1 -100, height1 -100 );
          setLocationRelativeTo(new Gui.Authentification());
          System.out.println(width1+","+height1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        bodyPanel = new javax.swing.JPanel();
        menu_panel = new javax.swing.JPanel();
        monProfilButton = new javax.swing.JButton();
        ajouterTrajetButton = new javax.swing.JButton();
        chercherTrajetButton = new javax.swing.JButton();
        deconexionButton = new javax.swing.JButton();
        gererMesTrajetButtom = new javax.swing.JButton();
        evaluerButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel.setMaximumSize(new java.awt.Dimension(1031, 578));
        jPanel.setMinimumSize(new java.awt.Dimension(1031, 578));

        bodyPanel.setBackground(new java.awt.Color(26, 120, 167));
        bodyPanel.setMaximumSize(new java.awt.Dimension(1031, 578));
        bodyPanel.setMinimumSize(new java.awt.Dimension(1031, 578));

        menu_panel.setBackground(new java.awt.Color(255, 255, 255));
        menu_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(51, 51, 51)));

        monProfilButton.setBackground(new java.awt.Color(255, 255, 255));
        monProfilButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/monprofil.png"))); // NOI18N
        monProfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monProfilButtonActionPerformed(evt);
            }
        });

        ajouterTrajetButton.setBackground(new java.awt.Color(255, 255, 255));
        ajouterTrajetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajoutcov.jpeg"))); // NOI18N
        ajouterTrajetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterTrajetButtonActionPerformed(evt);
            }
        });

        chercherTrajetButton.setBackground(new java.awt.Color(255, 255, 255));
        chercherTrajetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cherch.jpg"))); // NOI18N
        chercherTrajetButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chercherTrajetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherTrajetButtonActionPerformed(evt);
            }
        });

        deconexionButton.setBackground(new java.awt.Color(255, 255, 255));
        deconexionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dis.png"))); // NOI18N
        deconexionButton.setMaximumSize(new java.awt.Dimension(10, 10));
        deconexionButton.setMinimumSize(new java.awt.Dimension(10, 10));
        deconexionButton.setPreferredSize(new java.awt.Dimension(10, 10));

        gererMesTrajetButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gestion.jpg"))); // NOI18N
        gererMesTrajetButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gererMesTrajetButtomActionPerformed(evt);
            }
        });

        evaluerButton.setText("jButton1");
        evaluerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu_panelLayout = new javax.swing.GroupLayout(menu_panel);
        menu_panel.setLayout(menu_panelLayout);
        menu_panelLayout.setHorizontalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chercherTrajetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(monProfilButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
            .addComponent(ajouterTrajetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deconexionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gererMesTrajetButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(evaluerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu_panelLayout.setVerticalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addComponent(monProfilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ajouterTrajetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chercherTrajetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gererMesTrajetButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evaluerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(deconexionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        contentPanel.setForeground(new java.awt.Color(0, 153, 0));
        contentPanel.setMaximumSize(new java.awt.Dimension(100, 100));
        contentPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        contentPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monProfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monProfilButtonActionPerformed
       
        contentPanel.removeAll();
        contentPanel.add(new NouveauMonProfil());
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_monProfilButtonActionPerformed

    private void ajouterTrajetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterTrajetButtonActionPerformed
        contentPanel.removeAll();
        contentPanel.add(new AjouterTrajetPanel());
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_ajouterTrajetButtonActionPerformed

    private void gererMesTrajetButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gererMesTrajetButtomActionPerformed
        contentPanel.removeAll();
        contentPanel.add(new NouveauGererMesTrajet());
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_gererMesTrajetButtomActionPerformed

    private void chercherTrajetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherTrajetButtonActionPerformed
        contentPanel.removeAll();
        contentPanel.add(new NouveauRechercherTrajetPanel());
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_chercherTrajetButtonActionPerformed

    private void evaluerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluerButtonActionPerformed
        contentPanel.removeAll();
        contentPanel.add(new NouveauEvaluationAdherent());
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_evaluerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterTrajetButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton chercherTrajetButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deconexionButton;
    private javax.swing.JButton evaluerButton;
    private javax.swing.JButton gererMesTrajetButtom;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JButton monProfilButton;
    // End of variables declaration//GEN-END:variables
}
