/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui;
import Gui.Authentification;
import Gui.monProfilPanel;
import Entité.Reservation;
import static Gui.monProfilPanel.tableMesReservation;
import com.tn.doa.ReservationDAO;
import com.tn.tableModel.ReservationTableModel;
import com.tn.tableModel.TrajetTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author majdi
 */
public class RechercherTrajetPanel extends javax.swing.JPanel {

    /**
     * Creates new form RechercherTrajetPanel
     */
    public RechercherTrajetPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rechercher_trajetPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rechVilleDepart = new javax.swing.JTextField();
        rechVilleArrive = new javax.swing.JTextField();
        rechDate = new javax.swing.JTextField();
        rechercherBTN = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        BtnReserver = new javax.swing.JButton();
        trajetMap = new javax.swing.JPanel();
        trajetlabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTrajet = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new java.awt.BorderLayout());

        rechercher_trajetPanel.setBackground(new java.awt.Color(239, 228, 228));
        rechercher_trajetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        rechercher_trajetPanel.setMinimumSize(jPanel1.getMinimumSize());
        rechercher_trajetPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Date :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Ville d'Arrivée");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Ville de Départ");

        rechVilleDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechVilleDepartActionPerformed(evt);
            }
        });

        rechercherBTN.setText("Rechercher");
        rechercherBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherBTNActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 228, 174));
        jPanel4.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(138, 138, 212));
        jLabel15.setText("Les Derniers Annonces Publiées");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rechVilleDepart)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rechVilleArrive, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(rechDate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(rechercherBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rechercherBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(rechVilleDepart)
                    .addComponent(rechVilleArrive)
                    .addComponent(rechDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rechercher_trajetPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));
        jPanel3.setSize(rechercher_trajetPanel.getSize());

        BtnReserver.setText("Reserver ");
        BtnReserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReserverActionPerformed(evt);
            }
        });
        rechercher_trajetPanel.add(BtnReserver, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 395, 169, 32));

        trajetMap.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        trajetlabel.setText("<html><head></head><body><img src='http://maps.googleapis.com/maps/api/staticmap?&amp;size=500x500&amp;maptype=roadmap\\&markers=size:mid&th=color:0xff0000ff|weight:5|Tunis|Grombalia|Nabeul&amp;sensor=true'></body></html>");

        javax.swing.GroupLayout trajetMapLayout = new javax.swing.GroupLayout(trajetMap);
        trajetMap.setLayout(trajetMapLayout);
        trajetMapLayout.setHorizontalGroup(
            trajetMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trajetMapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trajetlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        trajetMapLayout.setVerticalGroup(
            trajetMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trajetlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );

        rechercher_trajetPanel.add(trajetMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 161, -1, -1));

        try{
            tableTrajet.setModel(new TrajetTableModel());
            tableTrajet.getColumnModel().getColumn(0).setMinWidth(0);
            tableTrajet.getColumnModel().getColumn(0).setMaxWidth(0);
            tableTrajet.getColumnModel().getColumn(0).setWidth(0);
        }catch(Exception ex ){System.out.print("erreurrr affichage tableauu");}
        jScrollPane2.setViewportView(tableTrajet);

        rechercher_trajetPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 161, 514, 216));

        jPanel1.add(rechercher_trajetPanel, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rechVilleDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechVilleDepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechVilleDepartActionPerformed

    private void rechercherBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherBTNActionPerformed
        String villedepart=rechVilleDepart.getText().toString();
        String villearrive=rechVilleArrive.getText().toString();
        String date=rechDate.getText().toString();
        if((!villedepart.equals(""))&&(!villearrive.equals(""))&&(!date.equals("")))
        {
            try {

                tableTrajet.setModel(new com.tn.tableModel.TrajetTableModel(villedepart,villearrive,date));
                tableTrajet.getColumnModel().getColumn(0).setMinWidth(0);
                tableTrajet.getColumnModel().getColumn(0).setMaxWidth(0);
                tableTrajet.getColumnModel().getColumn(0).setWidth(0);
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }}else if((!villedepart.equals(""))&&(!villearrive.equals(""))&&(date.equals("")))
            {
                try {
                    tableTrajet.setModel(new com.tn.tableModel.TrajetTableModel(villedepart,villearrive));
                    tableTrajet.getColumnModel().getColumn(0).setMinWidth(0);
                    tableTrajet.getColumnModel().getColumn(0).setMaxWidth(0);
                    tableTrajet.getColumnModel().getColumn(0).setWidth(0);
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if((!villedepart.equals(""))&&(villearrive.equals(""))&&(date.equals("")))
            {
                try {
                    tableTrajet.setModel(new com.tn.tableModel.TrajetTableModel(villedepart));
                    tableTrajet.getColumnModel().getColumn(0).setMinWidth(0);
                    tableTrajet.getColumnModel().getColumn(0).setMaxWidth(0);
                    tableTrajet.getColumnModel().getColumn(0).setWidth(0);
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                tableTrajet.setModel(new com.tn.tableModel.TrajetTableModel());
                tableTrajet.getColumnModel().getColumn(0).setMinWidth(0);
                tableTrajet.getColumnModel().getColumn(0).setMaxWidth(0);
                tableTrajet.getColumnModel().getColumn(0).setWidth(0);
            }

            //        for(int tr : com.tn.tableModel.TrajetTableModel.AllId){
                //            System.out.println(tr);
                //        }
            //
    }//GEN-LAST:event_rechercherBTNActionPerformed

    private void BtnReserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReserverActionPerformed
        Reservation reservation=new Reservation();
        ReservationDAO reservationDAO=new ReservationDAO();
        int x=tableTrajet.getSelectedRow();
        //
        reservation.setIdAdherent(Authentification.id_adherent);
        reservation.setIdTrajet((Integer) tableTrajet.getValueAt(x, 0));
        reservation.setPlaces((Integer)tableTrajet.getValueAt(x, 6));
        reservation.setDate((String) tableTrajet.getValueAt(x, 7));
        ///reservation.setHeure(tableTrajet.getValueAt(x, 8).toString());
        reservation.setVilleDepart(tableTrajet.getValueAt(x, 4).toString());
        reservation.setVilleArrivee(tableTrajet.getValueAt(x, 5).toString());
        //        System.out.println(reservation.getDate());
        reservationDAO.insertReservation(reservation);
        System.out.println(tableTrajet.getSelectedRow());
        System.out.println(Authentification.id_adherent);
        tableMesReservation.setModel(new ReservationTableModel(Authentification.id_adherent));
        
    }//GEN-LAST:event_BtnReserverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReserver;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField rechDate;
    private javax.swing.JTextField rechVilleArrive;
    private javax.swing.JTextField rechVilleDepart;
    private javax.swing.JButton rechercherBTN;
    private javax.swing.JPanel rechercher_trajetPanel;
    private javax.swing.JTable tableTrajet;
    private javax.swing.JPanel trajetMap;
    private javax.swing.JLabel trajetlabel;
    // End of variables declaration//GEN-END:variables
}
