/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui.admin;

import Entité.Administrateur;
import com.tn.doa.AdministrateurDAO;
import java.awt.Dimension;
import java.awt.Panel;

/**
 *
 * @author majdi
 */
public class Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form Acceuil
     */static  Dimension tailleEcran;
    public Acceuil() {
        initComponents();
         panelprofiladmin.add(new profiladminPanel());
         paneladherent.add(new ConsulterinfoAdherent());
         panelreclamation.add(new GererReclamation());
         panelstatistique.add(new GererlesSratistique());
         panelGererFAQ.add(new GenererFAQ());
         Dimension tailleEcran = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int width=(int)tailleEcran.getWidth();
          int height =(int)tailleEcran.getHeight();
          setSize(tailleEcran);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acceuilAdminGeneral = new javax.swing.JPanel();
        tabPrincipaleAdmin = new javax.swing.JTabbedPane();
        panelprofiladmin = new javax.swing.JPanel();
        paneladherent = new javax.swing.JPanel();
        panelreclamation = new javax.swing.JPanel();
        panelGererFAQ = new javax.swing.JPanel();
        panelstatistique = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabPrincipaleAdmin.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panelprofiladmin.setLayout(new java.awt.CardLayout());
        tabPrincipaleAdmin.addTab("Profil Admin", panelprofiladmin);

        paneladherent.setLayout(new java.awt.CardLayout());
        tabPrincipaleAdmin.addTab("Consulter info Adherent", paneladherent);

        panelreclamation.setLayout(new java.awt.CardLayout());
        tabPrincipaleAdmin.addTab("Gerer reclamation", panelreclamation);

        panelGererFAQ.setLayout(new java.awt.CardLayout());
        tabPrincipaleAdmin.addTab("Gerer FAQ", panelGererFAQ);

        panelstatistique.setLayout(new java.awt.CardLayout());
        tabPrincipaleAdmin.addTab("Gerer Statistique", panelstatistique);

        javax.swing.GroupLayout acceuilAdminGeneralLayout = new javax.swing.GroupLayout(acceuilAdminGeneral);
        acceuilAdminGeneral.setLayout(acceuilAdminGeneralLayout);
        acceuilAdminGeneralLayout.setHorizontalGroup(
            acceuilAdminGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPrincipaleAdmin)
        );
        acceuilAdminGeneralLayout.setVerticalGroup(
            acceuilAdminGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPrincipaleAdmin)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(acceuilAdminGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(acceuilAdminGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      AdministrateurDAO adDAO=new AdministrateurDAO();
      Administrateur ad=new Administrateur();
        ad=adDAO.findAdministrateurtById(Gui.admin.Authentification.id_administrateur);
        System.out.println(ad.getNom()+ " nom Admin");
        profiladminPanel.nomCompletText.setText(ad.getNom().toString());
        
        profiladminPanel.mailText.setText(ad.getLogin());
        
        profiladminPanel.loginText.setText(ad.getPrenom());
      
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acceuilAdminGeneral;
    private javax.swing.JPanel panelGererFAQ;
    private javax.swing.JPanel paneladherent;
    private static javax.swing.JPanel panelprofiladmin;
    private javax.swing.JPanel panelreclamation;
    private javax.swing.JPanel panelstatistique;
    private javax.swing.JTabbedPane tabPrincipaleAdmin;
    // End of variables declaration//GEN-END:variables
}
