/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui.admin;
import Entité.Adherent;
import Entité.Reclamation;
import com.tn.doa.AdherentDAO;
import com.tn.doa.ReclamationDAO;
import com.tn.tableModel.ReclamationsModel;
import IReport.RapportTest;
import com.tn.connect.MyConnection;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
/**
 *
 * @author majdi
 */
public class NouveauGererReclamation extends javax.swing.JPanel {

    /**
     * Creates new form NouveauGererReclamation
     */
    public NouveauGererReclamation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomReclamateurLabel = new javax.swing.JTextField();
        nomAdherentConcernéLabel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        prenomAdherentConcernéLabel = new javax.swing.JTextField();
        prenomReclamateurLabel = new javax.swing.JTextField();
        causeLabel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nbrReclamationLabel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        bloquerButton = new javax.swing.JButton();
        ReclamationNonTraiteeButton = new javax.swing.JButton();
        genererButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        reclamationTable = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.CardLayout());

        jLabel7.setText("Adherent Concerné");

        jLabel8.setText("Reclamatateur");

        nomReclamateurLabel.setEditable(false);
        nomReclamateurLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomReclamateurLabelActionPerformed(evt);
            }
        });

        nomAdherentConcernéLabel.setEditable(false);
        nomAdherentConcernéLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomAdherentConcernéLabelActionPerformed(evt);
            }
        });

        jLabel5.setText("NOM ");

        jLabel6.setText("Prenom");

        prenomAdherentConcernéLabel.setEditable(false);

        prenomReclamateurLabel.setEditable(false);
        prenomReclamateurLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomReclamateurLabelActionPerformed(evt);
            }
        });

        causeLabel.setEditable(false);
        causeLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                causeLabelActionPerformed(evt);
            }
        });

        jLabel10.setText("Cause");

        jLabel9.setText("nombre de reclamation");

        nbrReclamationLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbrReclamationLabelActionPerformed(evt);
            }
        });

        jLabel11.setText("Description");

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane4.setViewportView(descriptionTextArea);

        bloquerButton.setText("jButton3");
        bloquerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloquerButtonActionPerformed(evt);
            }
        });

        ReclamationNonTraiteeButton.setText("Réclamation non traitée");
        ReclamationNonTraiteeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReclamationNonTraiteeButtonActionPerformed(evt);
            }
        });

        genererButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genererButtonActionPerformed(evt);
            }
        });

        reclamationTable.setModel(new com.tn.tableModel.ReclamationsModel()
        );
        reclamationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reclamationTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(reclamationTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(739, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bloquerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genererButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(nomAdherentConcernéLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(prenomAdherentConcernéLabel)))
                            .addGap(59, 59, 59)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(prenomReclamateurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(nomReclamateurLabel)))
                        .addComponent(ReclamationNonTraiteeButton)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(42, 42, 42)
                                    .addComponent(causeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(nbrReclamationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(genererButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bloquerButton)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addGap(46, 46, 46)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(nomAdherentConcernéLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomReclamateurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(prenomAdherentConcernéLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prenomReclamateurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(causeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(nbrReclamationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ReclamationNonTraiteeButton))
                        .addComponent(jLabel11))
                    .addGap(52, 52, 52)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel3, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void nomReclamateurLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomReclamateurLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomReclamateurLabelActionPerformed

    private void nomAdherentConcernéLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomAdherentConcernéLabelActionPerformed
        // TODO add your handling code her

        int row =reclamationTable.getSelectedRow();
        String Table_Click = (reclamationTable.getModel().getValueAt(row, 0).toString());
        Reclamation reclamation=new Reclamation();

        nomAdherentConcernéLabel.setText(Table_Click);
    }//GEN-LAST:event_nomAdherentConcernéLabelActionPerformed

    private void prenomReclamateurLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomReclamateurLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomReclamateurLabelActionPerformed

    private void causeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_causeLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_causeLabelActionPerformed

    private void nbrReclamationLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbrReclamationLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbrReclamationLabelActionPerformed

    private void bloquerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloquerButtonActionPerformed
        // TODO add your handling code here:
        int row =reclamationTable.getSelectedRow();
        int id=(int) reclamationTable.getValueAt(row,0);
        System.out.println("id reclamation"+id);
        Reclamation reclamation=new Reclamation();
        ReclamationDAO reclamationDAO=new ReclamationDAO();
        reclamation=reclamationDAO.findReclamationById(id);
        AdherentDAO adherentDAO=new AdherentDAO();
        Adherent adherent=new Adherent();
        adherent=adherentDAO.findAdherentByIdSa(reclamation.getAdherentConcerné().getIdAdherent());
        int idAdherent=adherent.getIdAdherent();
        adherentDAO.updateDesactivéCompteAdherentSa(idAdherent);
    }//GEN-LAST:event_bloquerButtonActionPerformed

    private void ReclamationNonTraiteeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReclamationNonTraiteeButtonActionPerformed
        reclamationTable.setModel(new ReclamationsModel(2));
        genererButton.setVisible(true);
        genererButton.setText("Générer rapport");
        //  bloquerButton.setText("Bloquer");
        //bloquerButton.setVisible(true);

        ReclamationNonTraiteeButton.setVisible(false);

        genererButton.setVisible(true);

        /*  RapportTest rapportTest=new  RapportTest();
        try {
            rapportTest.report();
        } catch (JRException ex) {
            Logger.getLogger(Acceuil.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_ReclamationNonTraiteeButtonActionPerformed

    private void genererButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genererButtonActionPerformed
        // TODO add your handling code here:

        int row =reclamationTable.getSelectedRow();
        int id=(int) reclamationTable.getValueAt(row,0);
        System.out.println("id reclamation"+id);
        Reclamation reclamation=new Reclamation();
        ReclamationDAO reclamationDAO=new ReclamationDAO();
        reclamation=reclamationDAO.findReclamationById(id);
        AdherentDAO adherentDAO=new AdherentDAO();
        Adherent adherent=new Adherent();
        adherent=adherentDAO.findAdherentByIdSa(reclamation.getAdherentConcerné().getIdAdherent());
        if(adherent.getNombreReclamation()>=5)
        {
            System.out.println("bloquer");
            bloquerButton.setText("Bloquer");
            bloquerButton.setVisible(true);
        }

        RapportTest rapportTest=new  RapportTest();
        try {
            rapportTest.report(id);
        } catch (JRException ex) {
            Logger.getLogger(Acceuil.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_genererButtonActionPerformed

    private void reclamationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reclamationTableMouseClicked
        // TODO add your handling code here:

        int row =reclamationTable.getSelectedRow();
        String nomReclamateur= (reclamationTable.getModel().getValueAt(row, 1).toString());
        String prenomReclamateur = (reclamationTable.getModel().getValueAt(row, 2).toString());
        String nomAdherentConcerné=(reclamationTable.getModel().getValueAt(row, 3).toString());
        String prenomAdherentConcerné=(reclamationTable.getModel().getValueAt(row, 4).toString());
        String cause=(reclamationTable.getModel().getValueAt(row,5).toString());
        String description=(reclamationTable.getModel().getValueAt(row,6).toString());
        String nombreReclamation=(reclamationTable.getModel().getValueAt(row,7).toString());
        Reclamation reclamation=new Reclamation();

        prenomReclamateurLabel.setText(prenomReclamateur);
        nomReclamateurLabel.setText(nomReclamateur);
        nomAdherentConcernéLabel.setText(nomAdherentConcerné);
        prenomAdherentConcernéLabel.setText(prenomAdherentConcerné);
        causeLabel.setText(cause);
        descriptionTextArea.setText(description);
        nbrReclamationLabel.setText(nombreReclamation);
    }//GEN-LAST:event_reclamationTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReclamationNonTraiteeButton;
    private javax.swing.JButton bloquerButton;
    private javax.swing.JTextField causeLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton genererButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField nbrReclamationLabel;
    private javax.swing.JTextField nomAdherentConcernéLabel;
    private javax.swing.JTextField nomReclamateurLabel;
    private javax.swing.JTextField prenomAdherentConcernéLabel;
    private javax.swing.JTextField prenomReclamateurLabel;
    private javax.swing.JTable reclamationTable;
    // End of variables declaration//GEN-END:variables
}
