/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui.admin;

import Entité.Adherent;
import com.tn.connect.MyConnection;
import com.tn.doa.AdherentDAO;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.text.Document;
import javax.mail.Message;
import javax.mail.Transport;
import javax.mail.PasswordAuthentication;
import java.util.Properties;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import brouillons.Authentification;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.lowagie.text.pdf.PdfCell;
import com.tn.connect.MyConnection;
import com.tn.doa.AdherentDAO;
import com.tn.tableModel.gestionAdherent;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartRenderingInfo;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.entity.StandardEntityCollection;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.text.*;
import java.awt.print.*;
import javax.swing.JTable;
import javax.swing.text.Element;
/**
 *
 * @author majdi
 */
public class NouveauConsulterinfoAdherent extends javax.swing.JPanel {

    /**
     * Creates new form ConsulterinfoAdherent
     */
    public NouveauConsulterinfoAdherent() {
        initComponents();
        // findCombo();
        update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        adherentTable = new javax.swing.JTable();
        idadherent_lbl = new javax.swing.JLabel();
        nom_lbl = new javax.swing.JLabel();
        prenomadherent_lbl = new javax.swing.JLabel();
        adresseaderent_lbl = new javax.swing.JLabel();
        mdpAdherent_lbl = new javax.swing.JLabel();
        tel_lbl = new javax.swing.JLabel();
        idadherenttxt = new javax.swing.JTextField();
        nomadherentTxt = new javax.swing.JTextField();
        prenomAdhrentTxt = new javax.swing.JTextField();
        adresseAdherentTxt = new javax.swing.JTextField();
        mdpAdherentTXT = new javax.swing.JTextField();
        telAdherentTXT = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        nbr_recl_lbl = new javax.swing.JLabel();
        nbrReclamationsTxt = new javax.swing.JTextField();
        name_comboBox = new javax.swing.JComboBox();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        SubjectLabel = new javax.swing.JLabel();
        FromText = new javax.swing.JTextField();
        ToText = new javax.swing.JTextField();
        SubjectText = new javax.swing.JTextField();
        RapportBoutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmailText = new javax.swing.JTextArea();
        MailBoutton = new javax.swing.JButton();
        BloquerBoutton = new javax.swing.JButton();
        txtSearchAdherent = new javax.swing.JTextField();
        ImprimerBoutton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(927, 682));
        setMinimumSize(new java.awt.Dimension(927, 682));

        adherentTable.setModel(new gestionAdherent()
        );
        adherentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adherentTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(adherentTable);

        idadherent_lbl.setText("IdAdhérent");

        nom_lbl.setText("Nom");

        prenomadherent_lbl.setText("Prenom");

        adresseaderent_lbl.setText("adresse mail");

        mdpAdherent_lbl.setText("Mot de passe");

        tel_lbl.setText("tel");

        idadherenttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadherenttxtActionPerformed(evt);
            }
        });

        mdpAdherentTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdpAdherentTXTActionPerformed(evt);
            }
        });

        deleteButton.setText("Supprimer");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Modifier");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        nbr_recl_lbl.setText("Nombres de réclamations");

        nbrReclamationsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbrReclamationsTxtActionPerformed(evt);
            }
        });

        name_comboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                name_comboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        name_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_comboBoxActionPerformed(evt);
            }
        });

        fromLabel.setText("From");

        toLabel.setText("To");

        SubjectLabel.setText("Subject");

        ToText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToTextActionPerformed(evt);
            }
        });

        RapportBoutton.setText("Générer Rapport");
        RapportBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RapportBouttonActionPerformed(evt);
            }
        });

        jLabel4.setText("Veuillez entrez un Nom");

        jLabel5.setText("Selectionnez le Nom et prénom de l'adherent");

        EmailText.setColumns(20);
        EmailText.setRows(5);
        jScrollPane1.setViewportView(EmailText);

        MailBoutton.setText("Envoyer un Email");
        MailBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailBouttonActionPerformed(evt);
            }
        });

        BloquerBoutton.setText("Bloquer");
        BloquerBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloquerBouttonActionPerformed(evt);
            }
        });

        txtSearchAdherent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchAdherentKeyReleased(evt);
            }
        });

        ImprimerBoutton.setText("Imprimer");
        ImprimerBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimerBouttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 623, Short.MAX_VALUE)
                        .addComponent(SubjectLabel)
                        .addGap(43, 43, 43)
                        .addComponent(SubjectText, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 436, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MailBoutton)
                                .addGap(122, 122, 122)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(toLabel)
                                        .addGap(53, 53, 53))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ToText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FromText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adresseAdherentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idadherenttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomadherentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mdpAdherentTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prenomAdhrentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telAdherentTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nbrReclamationsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tel_lbl)
                            .addComponent(mdpAdherent_lbl))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BloquerBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RapportBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImprimerBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idadherent_lbl)
                                    .addComponent(nom_lbl)
                                    .addComponent(prenomadherent_lbl)
                                    .addComponent(adresseaderent_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nbr_recl_lbl))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap(795, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adresseAdherentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BloquerBoutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mdpAdherent_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mdpAdherentTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RapportBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tel_lbl)
                                    .addComponent(telAdherentTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearchAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idadherenttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nomadherentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(updateButton))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(prenomAdhrentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deleteButton)))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nbrReclamationsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImprimerBoutton))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubjectText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubjectLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MailBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)
                    .addComponent(idadherent_lbl)
                    .addGap(21, 21, 21)
                    .addComponent(nom_lbl)
                    .addGap(61, 61, 61)
                    .addComponent(prenomadherent_lbl)
                    .addGap(24, 24, 24)
                    .addComponent(adresseaderent_lbl)
                    .addGap(193, 193, 193)
                    .addComponent(nbr_recl_lbl)
                    .addContainerGap(253, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adherentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adherentTableMouseClicked

        try {

            int row =adherentTable.getSelectedRow();
            String Table_Click = (adherentTable.getModel().getValueAt(row, 0).toString());
            String requete ="select * from adherent where id_adherent='"+Table_Click+"'";

            Statement statement = MyConnection.getInstance().createStatement();
            PreparedStatement ps = MyConnection.getInstance().prepareStatement(requete);
            ResultSet resultat = ps.executeQuery();

            if (resultat.next())
            {

                String add1 =resultat.getString("id_adherent");
                idadherenttxt.setText(add1);
                String add2 =resultat.getString("nom");
                nomadherentTxt.setText(add2);
                String add3 =resultat.getString("prenom");
                prenomAdhrentTxt.setText(add3);
                String add4 =resultat.getString("adresse_mail");
                adresseAdherentTxt.setText(add4);
                String add5 =resultat.getString("mdp");
                mdpAdherentTXT.setText(add5);
                String add6 =resultat.getString("telephone");
                telAdherentTXT.setText(add6);
                String add7=resultat.getString("nombre_reclamation");
                nbrReclamationsTxt.setText(add7);

            }

        }

        catch (Exception e )
        {

            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_adherentTableMouseClicked

    private void idadherenttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadherenttxtActionPerformed

        idadherenttxt.setEditable(false);
    }//GEN-LAST:event_idadherenttxtActionPerformed
 private void update_table()
    {
        
    try {
        String sql = "select * from adherent";
        Statement statement = MyConnection.getInstance().createStatement();
          PreparedStatement ps = MyConnection.getInstance().prepareStatement(sql);
            ResultSet resultat =ps.executeQuery();
            adherentTable.setModel(DbUtils.resultSetToTableModel(resultat));
            
        
       
    
    }
    
    
    catch(Exception e)
    {
    
     JOptionPane.showMessageDialog(null, e);
    
    
    }
    
    
    }
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int p =JOptionPane.showConfirmDialog(null, "etes-vous sur de vouloir supprimer","delete",JOptionPane.YES_NO_OPTION);
        AdherentDAO adherentDAO=new AdherentDAO();
        if (p ==0)
        {
            int id= Integer.parseInt(idadherenttxt.getText());
            adherentDAO.deleteAdherent(id);

            String requete = "delete from adherent where id_adherent= ?";

            update_table();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed
public void update(Graphics g) {
        super.update(g);}
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        try
        {
            int id =Integer.parseInt(idadherenttxt.getText());
            String nom =nomadherentTxt.getText();
            String prenom =prenomAdhrentTxt.getText();
            String adresseMail =adresseAdherentTxt.getText();
            String mdp =mdpAdherentTXT.getText();
            int tel =Integer.parseInt(telAdherentTXT.getText());
            int breReclamation =Integer.parseInt(nbrReclamationsTxt.getText());

            AdherentDAO adherentDAO=new AdherentDAO();
            adherentDAO.updateAdherent(id, nom, prenom, adresseMail, mdp, tel, breReclamation);

        }

        catch(Exception e)
        {

            JOptionPane.showMessageDialog(null, e);

        }

        update_table();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void name_comboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_name_comboBoxPopupMenuWillBecomeInvisible
        AdherentDAO adherentDAO=new AdherentDAO();
        Authentification authentification=new Authentification();
        List<Adherent> listeAdherents=new ArrayList<Adherent>();
        listeAdherents=adherentDAO.DisplayAllAdhrernt();
        for(int i=0;i<listeAdherents.size();i++)
        {
            name_comboBox.addItem(listeAdherents.get(i).getNom()+" "+listeAdherents.get(i).getPrenom());
        }
        

    }//GEN-LAST:event_name_comboBoxPopupMenuWillBecomeInvisible

    private void name_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_comboBoxActionPerformed
       
        
        
        
        
        
    }//GEN-LAST:event_name_comboBoxActionPerformed

    private void ToTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToTextActionPerformed

    private void RapportBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RapportBouttonActionPerformed
        
                String value1 =idadherenttxt.getText();
                String value2 =nomadherentTxt.getText();
                String value3 =prenomAdhrentTxt.getText();
                String value4 =adresseAdherentTxt.getText();
                String value5 =mdpAdherentTXT.getText();
                String value6 =telAdherentTXT.getText();
                 String value7 =nbrReclamationsTxt.getText();
                
                
        try {
                  // pagesize.A4.rotate() pour voir le rapport dans IDE 
                   com.itextpdf.text.Document document = new com.itextpdf.text.Document(PageSize.A4.rotate());
                  PdfWriter writer= PdfWriter.getInstance(document, new FileOutputStream("rapport.pdf"));
                   
                  if ((new File("rapport.pdf")).exists()) {
 
			Process p = Runtime
			   .getRuntime()
			   .exec("rundll32 url.dll,FileProtocolHandler rapport.pdf");
			p.waitFor();
                                                                
		} else {
 
			System.out.println("File is not exists");
 
		}
 
                  
                  document.open();
                  // Date
                  document.add(new Paragraph(new Date().toString()));
                  document.add(new Paragraph("Rapport Statistiques", FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD, BaseColor.RED)));
                  document.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
                  
                  
                  // ajoute un tableau dans le rapport 
                  
//                  PdfPTable table = new PdfPTable(4);
//                  
//                   PdfPCell cell = new PdfPCell(new Paragraph("Informations Adhérents"));
//                     // le titre du tableau 
//                  cell.setColspan(10);
//                  cell.setBackgroundColor(BaseColor.GREEN);
//                  table.addCell(cell);
                  
                  
//                  table.addCell("Id Adhérent");
//                  table.addCell("Nom de l'adhérent");
//                  table.addCell("Prénom de l'adhérent");
//                  table.addCell("Numéro de l'adhérent");
//                  document.add(table);
                  // le titre du tableau 
                
                  
                  
                  
                  
                  // ajouter l'image dans le fichier pdf 
                  Image image = Image.getInstance("statistiques.png");
                  document.add(new Paragraph("statistiques.png"));
                  document.add(image);
                  
                  // document.add(new Paragraph("Salut sindoud", FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD, BaseColor.BLUE)));
                   
                   //document.add(new Paragraph (new Date().toString()));
                  
                 
                 PdfPTable table = new PdfPTable(6);
                 PdfPCell cell = new PdfPCell(new Paragraph("Titre"));
                 cell.setColspan(4);
               //  cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                 cell.setBackgroundColor(BaseColor.GREEN);
                 table.addCell("id de l'adherent");
                 table.addCell(value1);
                 table.addCell("Nom de l'adhérent");
                 table.addCell(value2);
                 table.addCell("Prénom de l'adhérent");
               table.addCell(value3);
                    table.addCell("adresse de l'adhérent");  
                     table.addCell(value4);
                    table.addCell("mot de passe de l'adherent");
                     table.addCell(value5);
                       table.addCell("tel de l'adherent ");
                        table.addCell(value6);
                          table.addCell("nombre de reclamations");
                           table.addCell(value7);
                    
                  document.add(table);
                  
                  
                  document.close();
                   //com.itextpdf.text.Image image1= com.itextpdf.text.Image.getInstance("statistiques.png");
                     // image1.scaleAbsolute(400,300);
                      //document.add(image1);
                      //PdfContentByte cb= writer.getDirectContent();
                   JOptionPane.showMessageDialog(null, "rapport enregistré");
              }
                
               catch(DocumentException | IOException | InterruptedException | HeadlessException e)
           {  
               
               JOptionPane.showMessageDialog(null, e);
               
               
               
           }
//
    }//GEN-LAST:event_RapportBouttonActionPerformed

    private void MailBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailBouttonActionPerformed
        String From =FromText.getText();
         String To =ToText.getText();
         String Subject = SubjectText.getText();
         String text= EmailText.getText();

         Properties pros= new Properties();
         pros.put("mail.smtp.host", "smtp.gmail.com");
         pros.put("mail.smtp.socketFactory.port", "465");
         pros.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
         pros.put("mail.smtp.auth","true");
         pros.put("mail.smtp.port", "465");
         
         
         Session session = Session.getDefaultInstance(pros,
                 
                 
                 new javax.mail.Authenticator() {
                     
                     
                     protected PasswordAuthentication getPasswordAuthentication(){
                        
                         return new PasswordAuthentication("covoiturage3a18@gmail.com", "sindasalma");
                     
                     }
}
                 
                 
                 );
         
         try {
             Message message= new MimeMessage(session);
             message.setFrom(new InternetAddress(From));
             message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(To));
             message.setSubject(Subject);
             message.setText(text);
             Transport.send(message);
             
             
             JOptionPane.showMessageDialog(null, "mail recu ");
         
         
         }
         catch(Exception e) {
         
         JOptionPane.showMessageDialog(null, "Vérifier les emails saisis");
         
         }
    }//GEN-LAST:event_MailBouttonActionPerformed

    private void BloquerBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloquerBouttonActionPerformed
             
        
        AdherentDAO adherentDAO=new AdherentDAO();
               int row=adherentTable.getSelectedRow();
                int id=(int) adherentTable.getValueAt(row,0);
               Adherent adherent=new Adherent();
               
               
               
               
               
       adherentDAO.setEetatAdherent(id);    }//GEN-LAST:event_BloquerBouttonActionPerformed

    private void txtSearchAdherentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchAdherentKeyReleased
       
        
          try{
              
              
               
                String requete=" select * from adherent where nom=?";
                Statement statement = MyConnection.getInstance().createStatement();
                 PreparedStatement ps = MyConnection.getInstance().prepareStatement(requete);
                 ps.setString(1, txtSearchAdherent.getText());
                 
                 ResultSet resultat = ps.executeQuery();
                 
                 if(resultat.next())
                 {
                 
                 String add1 = resultat.getString("id_adherent");
          idadherenttxt.setText(add1);
          String add2 =resultat.getString("nom");
          nomadherentTxt.setText(add2);
          String add3 =resultat.getString("prenom");
          prenomAdhrentTxt.setText(add3);
          String add4 =resultat.getString("adresse_mail");
          adresseAdherentTxt.setText(add4);
          String add5 =resultat.getString("mdp");
          mdpAdherentTXT.setText(add5);
          String add6 =resultat.getString("telephone");
          telAdherentTXT.setText(add6);
          String add7=resultat.getString("nombre_reclamation");
          nbrReclamationsTxt.setText(add7);
                 
                 }

               
               
               }
               catch(Exception e)
               {
               
               JOptionPane.showMessageDialog(null, e);
               
               }
        
        
        
    }//GEN-LAST:event_txtSearchAdherentKeyReleased

    private void ImprimerBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimerBouttonActionPerformed
       
        MessageFormat header = new MessageFormat("rapport imprimé");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        
            try {
            
            
            adherentTable.print(JTable.PrintMode.NORMAL,header,footer);
            
            }
            catch(java.awt.print.PrinterException e)
                
            {
            
            System.err.format("vous ne pouvez pas faire l'impression", e.getMessage());
            
            }
        
        
        
        
        
    }//GEN-LAST:event_ImprimerBouttonActionPerformed

    private void mdpAdherentTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdpAdherentTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdpAdherentTXTActionPerformed

    private void nbrReclamationsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbrReclamationsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbrReclamationsTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BloquerBoutton;
    private javax.swing.JTextArea EmailText;
    private javax.swing.JTextField FromText;
    private javax.swing.JButton ImprimerBoutton;
    private javax.swing.JButton MailBoutton;
    private javax.swing.JButton RapportBoutton;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JTextField SubjectText;
    private javax.swing.JTextField ToText;
    private javax.swing.JTable adherentTable;
    private javax.swing.JTextField adresseAdherentTxt;
    private javax.swing.JLabel adresseaderent_lbl;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel idadherent_lbl;
    private static javax.swing.JTextField idadherenttxt;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField mdpAdherentTXT;
    private javax.swing.JLabel mdpAdherent_lbl;
    private javax.swing.JComboBox name_comboBox;
    private javax.swing.JTextField nbrReclamationsTxt;
    private javax.swing.JLabel nbr_recl_lbl;
    private javax.swing.JLabel nom_lbl;
    private javax.swing.JTextField nomadherentTxt;
    private javax.swing.JTextField prenomAdhrentTxt;
    private javax.swing.JLabel prenomadherent_lbl;
    private javax.swing.JTextField telAdherentTXT;
    private javax.swing.JLabel tel_lbl;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField txtSearchAdherent;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
