/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui.admin;
import com.tn.connect.MyConnection;
import com.tn.doa.EvaluationDAO;
import com.tn.tableModel.EvaluationTable;
import java.awt.Color;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartRenderingInfo;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.entity.StandardEntityCollection;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.RectangleAnchor;
/**
 *
 * @author majdi
 */
public class NouveauStatistique extends javax.swing.JPanel {

    /**
     * Creates new form NouveauStatistique
     */
    public NouveauStatistique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idEvaluationLabel = new javax.swing.JLabel();
        idAdherentevalueLabel = new javax.swing.JLabel();
        idEvaluateurLabel = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();
        commentaireLabel = new javax.swing.JLabel();
        ReponseLabel = new javax.swing.JLabel();
        idEvaluationText = new javax.swing.JTextField();
        idAdherentEvaluéText = new javax.swing.JTextField();
        idEvaluateurText = new javax.swing.JTextField();
        noteTxt = new javax.swing.JTextField();
        commentaireTxt = new javax.swing.JTextField();
        RepTxt = new javax.swing.JTextField();
        StatistiquesBoutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemesEvaluation = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.CardLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(591, 457));
        jPanel1.setMinimumSize(new java.awt.Dimension(591, 457));

        idEvaluationLabel.setText("id evaluation");

        idAdherentevalueLabel.setText("id adhérent evalué");

        idEvaluateurLabel.setText("id evaluateur");

        noteLabel.setText("note");

        commentaireLabel.setText("commentaire");

        ReponseLabel.setText("Réponse");

        StatistiquesBoutton.setText("générer Statistique");
        StatistiquesBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatistiquesBouttonActionPerformed(evt);
            }
        });

        tablemesEvaluation.setModel(new  com.tn.tableModel.EvaluationTable());
        tablemesEvaluation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemesEvaluationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablemesEvaluation);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idEvaluationLabel)
                            .addComponent(idAdherentevalueLabel)
                            .addComponent(idEvaluateurLabel)
                            .addComponent(noteLabel)
                            .addComponent(commentaireLabel)
                            .addComponent(ReponseLabel))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idEvaluationText)
                            .addComponent(idAdherentEvaluéText)
                            .addComponent(idEvaluateurText)
                            .addComponent(noteTxt)
                            .addComponent(commentaireTxt)
                            .addComponent(RepTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(StatistiquesBoutton))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idEvaluationLabel)
                                .addGap(26, 26, 26)
                                .addComponent(idAdherentevalueLabel)
                                .addGap(27, 27, 27)
                                .addComponent(idEvaluateurLabel)
                                .addGap(25, 25, 25)
                                .addComponent(noteLabel)
                                .addGap(34, 34, 34)
                                .addComponent(commentaireLabel)
                                .addGap(27, 27, 27)
                                .addComponent(ReponseLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(commentaireTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(idEvaluationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(idAdherentEvaluéText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(idEvaluateurText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(noteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)))
                                .addGap(27, 27, 27)
                                .addComponent(RepTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(StatistiquesBoutton)))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void StatistiquesBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatistiquesBouttonActionPerformed

        int size=tablemesEvaluation.getRowCount();

        List<Double> notes=new ArrayList<Double>();
        List<Integer>  ids = new ArrayList<Integer>();
        List<String> noms=new ArrayList<String>();
        EvaluationDAO evaluationDAO=new EvaluationDAO();
        System.out.println("ouh ouh  "+size);
        //System.out.println(evaluationDAO.getMoyenneByAdherent(8));
        int idadh;
        float ess;
        for(int i=0;i<size;i++)
        {

            System.out.println(tablemesEvaluation.getValueAt(i,4).toString());
            idadh=Integer.parseInt(tablemesEvaluation.getValueAt(i,1).toString());
            String nom=(tablemesEvaluation.getValueAt(i,2).toString());
            // notes.add((new Double (tablemesEvaluation.getValueAt(i,2).toString())));
            System.out.println(" id adherent "+idadh);
            // System.out.println("moyenne "+);
            ess=evaluationDAO.getMoyenneByAdherent(idadh);
            System.out.println(ess);
            // notes.add((new Double (evaluationDAO.getMoyenneByAdherent((int) tablemesEvaluation.getValueAt(i,1)))));
            notes.add((new Double (ess)));
            ids.add((int) tablemesEvaluation.getValueAt(i,1));
            noms.add(nom);

        }

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(int i=0;i<size;i++)
        {

            dataset.setValue(new Double(notes.get(i)), "notes", new String (noms.get(i)));

        }

        //dataset.setValue(evaluationTable);

        JFreeChart chart = ChartFactory.createBarChart3D("Notes Adhérents", "Noms des adhérents", "Notes", dataset, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot p= chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame(" les notes des adhérents", chart);
        frame.setVisible(true);
        frame.setSize(700,800);
        ValueMarker marker = new ValueMarker(15);
        marker.setLabel(" seuil de l'évaluation ");
        marker.setLabelAnchor(RectangleAnchor.CENTER);
        marker.setPaint(Color.YELLOW);
        p.addRangeMarker(marker);
        p.setRangeGridlinePaint(Color.RED);

        try{

        }

        catch(Exception e)
        {}

        /*
        String note =noteTxt.getText();
        String idAdherent=idAdherentEvaluéText.getText();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(new Double(note), "notes", new Double(idAdherent));
        //dataset.setValue(evaluationTable);

        JFreeChart chart = ChartFactory.createBarChart3D("Notes Adhérents", "Id Adhérents", "Notes", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p= chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame(" les notes des adhérents", chart);
        frame.setVisible(true);
        frame.setSize(450,350);
        */
        try {

            final ChartRenderingInfo info = new ChartRenderingInfo(new StandardEntityCollection());
            final File file1=new File("statistiques.png");
            ChartUtilities.saveChartAsPNG(file1, chart, 600, 400,info);

        }

        catch(Exception e)
        {}
    }//GEN-LAST:event_StatistiquesBouttonActionPerformed

    private void tablemesEvaluationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemesEvaluationMouseClicked
        try {

            int row =tablemesEvaluation.getSelectedRow();
            String Table_Click = (tablemesEvaluation.getModel().getValueAt(row, 0).toString());
            String requete ="select * from evaluation where id_evaluation='"+Table_Click+"'";

            Statement statement = MyConnection.getInstance().createStatement();
            PreparedStatement ps = MyConnection.getInstance().prepareStatement(requete);
            ResultSet resultat = ps.executeQuery();

            if (resultat.next())
            {

                String add1 =resultat.getString("id_evaluation");
                idEvaluationText.setText(add1);

                String add2 =""+resultat.getInt(2);

                idAdherentEvaluéText.setText(add2);
                String add3 =resultat.getString("id_evaluateur");
                idEvaluateurText.setText(add3);
                String add4 =resultat.getString("note");
                noteTxt.setText(add4);
                String add5 =resultat.getString("commentaire");
                commentaireTxt.setText(add5);
                String add6 =resultat.getString("reponse");
                RepTxt.setText(add6);

            }

        }

        catch (Exception e )
        {

            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_tablemesEvaluationMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RepTxt;
    private javax.swing.JLabel ReponseLabel;
    private javax.swing.JButton StatistiquesBoutton;
    private javax.swing.JLabel commentaireLabel;
    private javax.swing.JTextField commentaireTxt;
    private javax.swing.JTextField idAdherentEvaluéText;
    private javax.swing.JLabel idAdherentevalueLabel;
    private javax.swing.JLabel idEvaluateurLabel;
    private javax.swing.JTextField idEvaluateurText;
    private javax.swing.JLabel idEvaluationLabel;
    private javax.swing.JTextField idEvaluationText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JTextField noteTxt;
    private javax.swing.JTable tablemesEvaluation;
    // End of variables declaration//GEN-END:variables
}
