/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui.admin;
import Entité.Faq;
import Mail.MailToSend;
import com.tn.connect.MyConnection;
import com.tn.doa.FaqDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author majdi
 */
public class NouveauGererFaq extends javax.swing.JPanel {

    /**
     * Creates new form NouveauGererFaq
     */
    public NouveauGererFaq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSplitPane5 = new javax.swing.JSplitPane();
        leftSplitFAQ3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        faqTable3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        objetfaq = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        objettxt1 = new javax.swing.JTextField();
        contenutxt1 = new javax.swing.JTextField();
        Ajouter = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jSplitPane5.setDividerLocation(350);
        jSplitPane5.setDividerSize(8);
        jSplitPane5.setOneTouchExpandable(true);

        leftSplitFAQ3.setBackground(new java.awt.Color(204, 204, 204));
        leftSplitFAQ3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des FAQ"));

        faqTable3.setModel(new com.tn.tableModel.FaqTable());
        faqTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faqTable3MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(faqTable3);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Table informations FAQ:");

        javax.swing.GroupLayout leftSplitFAQ3Layout = new javax.swing.GroupLayout(leftSplitFAQ3);
        leftSplitFAQ3.setLayout(leftSplitFAQ3Layout);
        leftSplitFAQ3Layout.setHorizontalGroup(
            leftSplitFAQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitFAQ3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftSplitFAQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        leftSplitFAQ3Layout.setVerticalGroup(
            leftSplitFAQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSplitFAQ3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jSplitPane5.setLeftComponent(leftSplitFAQ3);

        jLabel4.setText("Objet :");

        jLabel5.setText("Contenu :");

        objettxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objettxt1ActionPerformed(evt);
            }
        });

        contenutxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contenutxt1ActionPerformed(evt);
            }
        });

        Ajouter.setText("Ajouter");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout objetfaqLayout = new javax.swing.GroupLayout(objetfaq);
        objetfaq.setLayout(objetfaqLayout);
        objetfaqLayout.setHorizontalGroup(
            objetfaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objetfaqLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(objetfaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(objetfaqLayout.createSequentialGroup()
                        .addGroup(objetfaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(objetfaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contenutxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(objettxt1)))
                    .addGroup(objetfaqLayout.createSequentialGroup()
                        .addComponent(Ajouter)
                        .addGap(47, 47, 47)
                        .addComponent(Supprimer)
                        .addGap(49, 49, 49)
                        .addComponent(Modifier)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        objetfaqLayout.setVerticalGroup(
            objetfaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objetfaqLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(objetfaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(objettxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(objetfaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(contenutxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(objetfaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jSplitPane5.setRightComponent(objetfaq);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void faqTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faqTable3MouseClicked
        //System.out.println(fa);
        int row = faqTable3.getSelectedRow();
        String table_click = (faqTable3.getModel().getValueAt(row, 0).toString());
        FaqDAO fdao = new FaqDAO();
        Faq f = fdao.findFaqById(Integer.parseInt(table_click));

        objettxt1.setText(f.getObjet());
        contenutxt1.setText(f.getContenu());
    }//GEN-LAST:event_faqTable3MouseClicked

    private void objettxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objettxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_objettxt1ActionPerformed

    private void contenutxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contenutxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contenutxt1ActionPerformed

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed

        FaqDAO faqDAO=new FaqDAO();
        Faq faq=new Faq();
        faq.setObjet(objettxt1.getText());
        faq.setContenu(contenutxt1.getText());
        faqDAO.insertFaq(faq);

        update_table();
    }//GEN-LAST:event_AjouterActionPerformed
 private void update_table(){
    try{
    String sql = " select * from faq";
    PreparedStatement ps = MyConnection.getInstance().prepareStatement(sql);
    ResultSet result=ps.executeQuery();
    faqTable3.setModel(DbUtils.resultSetToTableModel(result));
    
    }
    catch(Exception e)
    {
     JOptionPane.showMessageDialog(null, e);   
    }
    }
    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
        FaqDAO FaqDAO=new FaqDAO();
        int row=faqTable3.getSelectedRow();
        int id=(int)faqTable3.getValueAt(row,0);
        FaqDAO.deleteFaq(id);

        update_table();
    }//GEN-LAST:event_SupprimerActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        try {

            int row=faqTable3.getSelectedRow();
            int id=(int)faqTable3.getValueAt(row,0);
            String obj =objettxt1.getText();
            String cont =contenutxt1.getText();
            Faq faq=new Faq();
            faq.setContenu(cont);
            faq.setObjet(obj);
            FaqDAO faqDAO = new FaqDAO();
            faqDAO.updateFaq(faq,id);
            MailToSend mailToSend=new MailToSend();
            String objet="Modification d'un Frequent Asked Question "+objettxt1;
            String contenu="Faq modifiée : "+contenutxt1;

            MailToSend.sendMessage(objet, contenu,"torjmen.salma@gmail.com","olfa.ayed@esprit.tn");

            JOptionPane.showMessageDialog(null, "Faq modifié avec succes");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        update_table();
    }//GEN-LAST:event_ModifierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Supprimer;
    private javax.swing.JTextField contenutxt1;
    private javax.swing.JTable faqTable;
    private javax.swing.JTable faqTable1;
    private javax.swing.JTable faqTable2;
    private javax.swing.JTable faqTable3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JPanel leftSplitFAQ;
    private javax.swing.JPanel leftSplitFAQ1;
    private javax.swing.JPanel leftSplitFAQ2;
    private javax.swing.JPanel leftSplitFAQ3;
    private javax.swing.JPanel objetfaq;
    private javax.swing.JTextField objettxt1;
    // End of variables declaration//GEN-END:variables
}
