/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui.admin;
import com.tn.tableModel.TrajetModel;
import Tools.Gmail;
import brouillons.Authentification;
import com.tn.doa.TrajetDAO;
import java.util.ArrayList;
import javax.swing.JTabbedPane;
import javax.swing.table.TableModel;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

/**
 *
 * @author majdi
 */
public class NouveauNotificationsAdministrateur extends javax.swing.JPanel {
 TrajetDAO  trajetDAO = new TrajetDAO();
        Gmail gmail = new Gmail();
        
        private final String e_mail_condition_climatique= "Cher Conducteur , ici le test de la prevention (climat)";
        private final String e_mail_condition_embouteillage= "Cher Conducteur , ici le test de la prevention (embouteillage)";
        private final String e_mail_condition_securite= "Cher Conducteur , ici le test de la prevention (securite)";

     public  ArrayList<String> list_ville_arr = new ArrayList<String>();
     public  ArrayList<String> list_Emails = new ArrayList<String>();
    /**
     * Creates new form NouveauNotificationsAdministrateur
     */
    public NouveauNotificationsAdministrateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gov2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ville2 = new javax.swing.JComboBox();
        jourCombo = new javax.swing.JComboBox();
        moisCombo = new javax.swing.JComboBox();
        anneeCombo = new javax.swing.JComboBox();
        rafraichir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Climat = new javax.swing.JButton();
        button_securite = new javax.swing.JButton();
        embouteillage_mail = new javax.swing.JButton();
        all_trajets = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jTable1.setModel(new TrajetModel());
        jTable1.getColumnModel().getColumn(14).setMinWidth(0);
        jTable1.getColumnModel().getColumn(14).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(14).setWidth(0);
        jTable1.getColumnModel().getColumn(4).setMinWidth(0);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(4).setWidth(0);
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(5).setWidth(0);
        jTable1.getColumnModel().getColumn(6).setMinWidth(0);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(6).setWidth(0);
        jTable1.getColumnModel().getColumn(7).setMinWidth(0);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(7).setWidth(0);
        jTable1.getColumnModel().getColumn(8).setMinWidth(0);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(8).setWidth(0);
        jTable1.getColumnModel().getColumn(9).setMinWidth(0);
        jTable1.getColumnModel().getColumn(9).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(9).setWidth(0);
        jScrollPane4.setViewportView(jTable1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notifier les Conducteurs D'un Probleme \n", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel4.setText("Jour de Depart :");

        jLabel5.setText("Destination : ");

        gov2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ariana", "Béja", "BenArous", "Bizerte", "Gabès", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kébili", "LaManouba", "LeKef", "Mahdia", "Médenine", "Monastir", "Nabeul", "Sfax", "SidiBouzid", "Siliana", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouan" }));
        gov2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gov2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Gouvernorat :");

        jLabel7.setText("Ville :");

        jourCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        moisCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        anneeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2014" }));

        rafraichir.setText("Rafraichir la Base");
        rafraichir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rafraichirActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notifier les Conducteurs concernes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14)))); // NOI18N

        Climat.setText("Condition climatique");
        Climat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClimatActionPerformed(evt);
            }
        });

        button_securite.setText("Problemes securitaires");
        button_securite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_securiteActionPerformed(evt);
            }
        });

        embouteillage_mail.setText("Embouteillage");
        embouteillage_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embouteillage_mailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(embouteillage_mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_securite, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(Climat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Climat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_securite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(embouteillage_mail)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jourCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moisCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anneeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rafraichir)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gov2, 0, 114, Short.MAX_VALUE)
                                .addComponent(ville2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(198, 198, 198)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jourCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moisCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anneeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(gov2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ville2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rafraichir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        all_trajets.setText("Get All Trajets");
        all_trajets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_trajetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(all_trajets, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(all_trajets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void gov2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gov2ActionPerformed

        switch (gov2.getSelectedIndex()) {
            case 0 :

            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Ariana");
            list_ville_arr.add("Raoued");
            list_ville_arr.add("LaSoukra");
            list_ville_arr.add("SidiThabet");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }

            break;
        }

        // ***************************************************************
        switch (gov2.getSelectedIndex()) {
            case 1 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Beja");
            list_ville_arr.add("MedjezEl_Bab");
            list_ville_arr.add("Testour");
            list_ville_arr.add("Téboursouk");
            list_ville_arr.add("Nefza");
            list_ville_arr.add("Amdoun");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }

            break;
        }
        //***********************************************************

        switch (gov2.getSelectedIndex()) {
            case 2 :

            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("ElMourouj");
            list_ville_arr.add("BenArous");
            list_ville_arr.add("Radès");
            list_ville_arr.add("HammamLif");
            list_ville_arr.add("Ezzahra");
            list_ville_arr.add("Mornag");
            list_ville_arr.add("HammamChott");
            list_ville_arr.add("Mégrine");
            list_ville_arr.add("Khalidia");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }

        //*********************************************************
        switch (gov2.getSelectedIndex()) {
            case 3 :

            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Bizerte");
            list_ville_arr.add("Mateur");
            list_ville_arr.add("RasJebel");
            list_ville_arr.add("MenzelJemil");
            list_ville_arr.add("Tinja");
            list_ville_arr.add("ElAlia");
            list_ville_arr.add("MenzelAbderrahmane");
            list_ville_arr.add("MenzelBourguiba");
            list_ville_arr.add("RafRaf");
            list_ville_arr.add("GharElMelh");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // ***************************************************************

        switch (gov2.getSelectedIndex()) {
            case 4 :

            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Gabès");
            list_ville_arr.add("ElHamma");
            list_ville_arr.add("Ghannouch");
            list_ville_arr.add("Mareth");
            list_ville_arr.add("Métouia");
            list_ville_arr.add("Oudhref");
            list_ville_arr.add("Zarat");
            list_ville_arr.add("Matmata");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // ***************************************************************

        switch (gov2.getSelectedIndex()) {
            case 5 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Gafsa");
            list_ville_arr.add("Métlaoui");
            list_ville_arr.add("ElKsar");
            list_ville_arr.add("Redeyef");
            list_ville_arr.add("ElGuettar");
            list_ville_arr.add("Mdhila");
            list_ville_arr.add("Sened");
            list_ville_arr.add("Matmata");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // ***************************************************************

        switch (gov2.getSelectedIndex()) {
            case 6 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Jendouba");
            list_ville_arr.add("BouSalem");
            list_ville_arr.add("Ghardimaou");
            list_ville_arr.add("Tabarka");
            list_ville_arr.add("AïnDraham");
            list_ville_arr.add("Fernana");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // ***************************************************************

        switch (gov2.getSelectedIndex()) {
            case 7 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Kairouan");
            list_ville_arr.add("Oueslatia");
            list_ville_arr.add("Sbikha");
            list_ville_arr.add("Haffouz");
            list_ville_arr.add("BouHajla");
            list_ville_arr.add("ElAlâa");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // ***************************************************************

        switch (gov2.getSelectedIndex()) {
            case 8 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Kasserine");
            list_ville_arr.add("Fériana");
            list_ville_arr.add("Sbeïtla");
            list_ville_arr.add("Thala");
            list_ville_arr.add("Haïdra");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // ***************************************************************

        switch (gov2.getSelectedIndex()) {
            case 9 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Douz");
            list_ville_arr.add("Kébili");
            list_ville_arr.add("Jemna");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // ***************************************************************

        switch (gov2.getSelectedIndex()) {
            case 10 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("DouarHicher");
            list_ville_arr.add("OuedEllil");
            list_ville_arr.add("LaManouba");
            list_ville_arr.add("Djedeida");
            list_ville_arr.add("DenDen");
            list_ville_arr.add("Tebourba");
            list_ville_arr.add("Mornaguia");
            list_ville_arr.add("BorjElAmri");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }

        // ********************* Le Kef******************

        switch (gov2.getSelectedIndex()) {
            case 11 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("LeKef");
            list_ville_arr.add("Tajerouine");
            list_ville_arr.add("Dahmani");
            list_ville_arr.add("Sers");
            list_ville_arr.add("Jérissa");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }

        // ***********************************Mahdia******************

        switch (gov2.getSelectedIndex()) {
            case 12 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Mahdia");
            list_ville_arr.add("KsourEssef");
            list_ville_arr.add("Chebba");
            list_ville_arr.add("ElJem");
            list_ville_arr.add("Rejiche");
            list_ville_arr.add("Essouassi");
            list_ville_arr.add("BouMerdes");
            list_ville_arr.add("Hebira");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // ******************************medenine*****************************

        switch (gov2.getSelectedIndex()) {
            case 13 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Zarzis");
            list_ville_arr.add("Djerba");
            list_ville_arr.add("Médenine");
            list_ville_arr.add("BenGardane");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }

        // ******************************Monastir*****************************

        switch (gov2.getSelectedIndex()) {
            case 14 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Monastir");
            list_ville_arr.add("Moknine");
            list_ville_arr.add("Jemmal");
            list_ville_arr.add("KsarHellal");
            list_ville_arr.add("Sahline");
            list_ville_arr.add("MenzelKamel");
            list_ville_arr.add("Sayada");
            list_ville_arr.add("Bembla");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;

        }

        //****************************Nabeul****************************

        switch (gov2.getSelectedIndex()) {
            case 15 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Hammamet");
            list_ville_arr.add("Nabeul");
            list_ville_arr.add("Kélibia");
            list_ville_arr.add("DarChaâbane");
            list_ville_arr.add("Korba");
            list_ville_arr.add("MenzelTemime");
            list_ville_arr.add("Soliman");
            list_ville_arr.add("Grombalia");
            list_ville_arr.add("MenzelBouzelfa");
            list_ville_arr.add("BouArgoub");
            list_ville_arr.add("Korbous");
            list_ville_arr.add("Tazarka");
            list_ville_arr.add("ElMaâmoura");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;

        }              // ***********************Sfax******************************

        switch (gov2.getSelectedIndex()) {
            case 16 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Sfax");
            list_ville_arr.add("SakietEzzit");
            list_ville_arr.add("Gremda");
            list_ville_arr.add("Skhira");
            list_ville_arr.add("Jebiniana");
            list_ville_arr.add("Agarebe");
            list_ville_arr.add("Kerkennah");
            list_ville_arr.add("Mahrès");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // *********************sidi bouzid**************************

        switch (gov2.getSelectedIndex()) {
            case 17 :
            list_ville_arr.clear();

            ville2.removeAllItems();

            list_ville_arr.add("SidiBouzid");
            list_ville_arr.add("Meknassy");
            list_ville_arr.add("Regueb");
            list_ville_arr.add("Mezzouna");
            list_ville_arr.add("SidiAliBenAoun");
            list_ville_arr.add("BirElHafey");
            list_ville_arr.add("Jilma");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }

        // **************************Siliana****************************

        switch (gov2.getSelectedIndex()) {
            case 18 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Siliana");
            list_ville_arr.add("Makthar");
            list_ville_arr.add("Gaâfour");
            list_ville_arr.add("Bargou");
            list_ville_arr.add("Rouhia");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // **************************Sousse********************************

        switch (gov2.getSelectedIndex()) {
            case 19 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Sousse");
            list_ville_arr.add("M'saken");
            list_ville_arr.add("Akouda");
            list_ville_arr.add("Ezzouhour");
            list_ville_arr.add("Enfida");
            list_ville_arr.add("Bouficha");
            list_ville_arr.add("Hergla");
            list_ville_arr.add("Messaadine");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // *******************************tatouine***************************

        switch (gov2.getSelectedIndex()) {
            case 20 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Tataouine");
            list_ville_arr.add("Ghomrassen");
            list_ville_arr.add("Remada");
            list_ville_arr.add("Dehiba");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }

            break;
        }
        // ***************************Tozeur***************************

        switch (gov2.getSelectedIndex()) {
            case 21 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Tozeur");
            list_ville_arr.add("Nefta");
            list_ville_arr.add("Degache");
            list_ville_arr.add("ElHammaduJérid");
            list_ville_arr.add("Tamerza");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // *****************************Tunis**************************

        switch (gov2.getSelectedIndex()) {
            case 22 :
            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("Tunis");
            list_ville_arr.add("SidiHassine");
            list_ville_arr.add("LaMarsa");
            list_ville_arr.add("LeBardo");
            list_ville_arr.add("LeKram");
            list_ville_arr.add("LaGoulette");
            list_ville_arr.add("Carthage");
            list_ville_arr.add("SidiBouSaïd");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }
        // **************************Zaghouane****************************

        switch (gov2.getSelectedIndex()) {
            case 23 :

            list_ville_arr.clear();
            ville2.removeAllItems();

            list_ville_arr.add("ElFahs");
            list_ville_arr.add("Zaghouan");
            list_ville_arr.add("Zriba");
            list_ville_arr.add("BirMcherga");
            list_ville_arr.add("Nadhour");

            int blasa =0;
            for (int i = 0 ; i < list_ville_arr.size(); i++) {
                ville2.insertItemAt(list_ville_arr.get(i),blasa);
                blasa++;
            }
            break;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_gov2ActionPerformed

    private void rafraichirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rafraichirActionPerformed
        jTable1.setModel(new TrajetModel(ville2.getSelectedItem().toString(),jourCombo.getSelectedItem()+"/" +moisCombo.getSelectedItem()+"/"+anneeCombo.getSelectedItem()));
        // cacher les champs inutiles
        jTable1.getColumnModel().getColumn(14).setMinWidth(0);
        jTable1.getColumnModel().getColumn(14).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(14).setWidth(0);
        jTable1.getColumnModel().getColumn(4).setMinWidth(0);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(4).setWidth(0);
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(5).setWidth(0);
        jTable1.getColumnModel().getColumn(6).setMinWidth(0);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(6).setWidth(0);
        jTable1.getColumnModel().getColumn(7).setMinWidth(0);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(7).setWidth(0);
        jTable1.getColumnModel().getColumn(8).setMinWidth(0);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(8).setWidth(0);
        jTable1.getColumnModel().getColumn(9).setMinWidth(0);
        jTable1.getColumnModel().getColumn(9).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(9).setWidth(0);

    }//GEN-LAST:event_rafraichirActionPerformed

    private void ClimatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClimatActionPerformed

        // retourne la liste des emails des conducteurs qui ont un trajet le jours X et la destination X

        list_Emails= (ArrayList<String>) trajetDAO.DisplayAllEmails(ville2.getSelectedItem().toString(),jourCombo.getSelectedItem()+"/" +moisCombo.getSelectedItem()+"/"+anneeCombo.getSelectedItem());

        for(int i =0 ; i<list_Emails.size(); i++) {

            gmail.subject = "Equipe Administration Covoiturage--Prevention";
            gmail.contenu=e_mail_condition_climatique;
            gmail.adresse_destination=list_Emails.get(i);

            gmail.sendMail();

        }

    }//GEN-LAST:event_ClimatActionPerformed

    private void button_securiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_securiteActionPerformed
        list_Emails= (ArrayList<String>) trajetDAO.DisplayAllEmails(ville2.getSelectedItem().toString(),jourCombo.getSelectedItem()+"/" +moisCombo.getSelectedItem()+"/"+anneeCombo.getSelectedItem());

        for(int i =0 ; i<list_Emails.size(); i++) {

            gmail.subject = "Equipe Administration Covoiturage--Prevention";
            gmail.contenu=e_mail_condition_securite;
            gmail.adresse_destination=list_Emails.get(i);

            gmail.sendMail();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_button_securiteActionPerformed

    private void embouteillage_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embouteillage_mailActionPerformed

        list_Emails= (ArrayList<String>) trajetDAO.DisplayAllEmails(ville2.getSelectedItem().toString(),jourCombo.getSelectedItem()+"/" +moisCombo.getSelectedItem()+"/"+anneeCombo.getSelectedItem());

        for(int i =0 ; i<list_Emails.size(); i++) {

            gmail.subject = "Equipe Administration Covoiturage--Prevention";
            gmail.contenu=e_mail_condition_embouteillage;
            gmail.adresse_destination=list_Emails.get(i);

            gmail.sendMail();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_embouteillage_mailActionPerformed

    private void all_trajetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_trajetsActionPerformed

        jTable1.setModel(new TrajetModel());

        // cacher les champs inutiles
        jTable1.getColumnModel().getColumn(14).setMinWidth(0);
        jTable1.getColumnModel().getColumn(14).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(14).setWidth(0);
        jTable1.getColumnModel().getColumn(4).setMinWidth(0);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(4).setWidth(0);
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(5).setWidth(0);
        jTable1.getColumnModel().getColumn(6).setMinWidth(0);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(6).setWidth(0);
        jTable1.getColumnModel().getColumn(7).setMinWidth(0);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(7).setWidth(0);
        jTable1.getColumnModel().getColumn(8).setMinWidth(0);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(8).setWidth(0);
        jTable1.getColumnModel().getColumn(9).setMinWidth(0);
        jTable1.getColumnModel().getColumn(9).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(9).setWidth(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_all_trajetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Climat;
    private javax.swing.JButton all_trajets;
    private javax.swing.JComboBox anneeCombo;
    private javax.swing.JButton button_securite;
    private javax.swing.JButton embouteillage_mail;
    private javax.swing.JComboBox gov2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jourCombo;
    private javax.swing.JComboBox moisCombo;
    private javax.swing.JButton rafraichir;
    private javax.swing.JComboBox ville2;
    // End of variables declaration//GEN-END:variables
}
