/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui.admin;
import Entité.Adherent;
import Entité.Reclamation;
import com.tn.doa.AdherentDAO;
import com.tn.doa.ReclamationDAO;
import com.tn.tableModel.ReclamationsModel;
import IReport.RapportTest;
import com.tn.connect.MyConnection;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
/**
 *
 * @author majdi
 */
public class NouveauGererReclamation extends javax.swing.JPanel {

    /**
     * Creates new form NouveauGererReclamation
     */
    public NouveauGererReclamation() {
        initComponents();
        genererButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bloquerButton = new javax.swing.JButton();
        ReclamationNonTraiteeButton = new javax.swing.JButton();
        genererButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        reclamationTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nomAdherentConcernéLabel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prenomAdherentConcernéLabel = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        nomReclamateurLabel = new javax.swing.JTextField();
        prenomReclamateurLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        causeLabel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nbrReclamationLabel = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.CardLayout());

        bloquerButton.setText("Bloquer");
        bloquerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloquerButtonActionPerformed(evt);
            }
        });

        ReclamationNonTraiteeButton.setText("Réclamation non traitée");
        ReclamationNonTraiteeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReclamationNonTraiteeButtonActionPerformed(evt);
            }
        });

        genererButton.setText("Generer Un Rapport Detaille");
        genererButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genererButtonActionPerformed(evt);
            }
        });

        reclamationTable.setModel(new com.tn.tableModel.ReclamationsModel()
        );
        reclamationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reclamationTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(reclamationTable);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adherent Concerne", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        jLabel5.setText("Nom :");

        nomAdherentConcernéLabel.setEditable(false);
        nomAdherentConcernéLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomAdherentConcernéLabelActionPerformed(evt);
            }
        });

        jLabel6.setText("Prenom :");

        prenomAdherentConcernéLabel.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prenomAdherentConcernéLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(nomAdherentConcernéLabel))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomAdherentConcernéLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(prenomAdherentConcernéLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reclamateur", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        nomReclamateurLabel.setEditable(false);
        nomReclamateurLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomReclamateurLabelActionPerformed(evt);
            }
        });

        prenomReclamateurLabel.setEditable(false);
        prenomReclamateurLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomReclamateurLabelActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom :");

        jLabel2.setText("Prenom :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(nomReclamateurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prenomReclamateurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomReclamateurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prenomReclamateurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel10.setText("Cause:");

        causeLabel.setEditable(false);
        causeLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                causeLabelActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre de Reclamations :");

        nbrReclamationLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbrReclamationLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(causeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(nbrReclamationLabel)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(causeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nbrReclamationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane4.setViewportView(descriptionTextArea);

        jLabel11.setText("Description :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(genererButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReclamationNonTraiteeButton)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(395, 395, 395))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloquerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReclamationNonTraiteeButton)
                            .addComponent(genererButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bloquerButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel3, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void nomReclamateurLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomReclamateurLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomReclamateurLabelActionPerformed

    private void nomAdherentConcernéLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomAdherentConcernéLabelActionPerformed
        // TODO add your handling code her

        int row =reclamationTable.getSelectedRow();
        String Table_Click = (reclamationTable.getModel().getValueAt(row, 0).toString());
        Reclamation reclamation=new Reclamation();

        nomAdherentConcernéLabel.setText(Table_Click);
    }//GEN-LAST:event_nomAdherentConcernéLabelActionPerformed

    private void prenomReclamateurLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomReclamateurLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomReclamateurLabelActionPerformed

    private void causeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_causeLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_causeLabelActionPerformed

    private void nbrReclamationLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbrReclamationLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbrReclamationLabelActionPerformed

    private void bloquerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloquerButtonActionPerformed
        // TODO add your handling code here:
        int row =reclamationTable.getSelectedRow();
        int id=(int) reclamationTable.getValueAt(row,0);
        System.out.println("id reclamation"+id);
        Reclamation reclamation=new Reclamation();
        ReclamationDAO reclamationDAO=new ReclamationDAO();
        reclamation=reclamationDAO.findReclamationById(id);
        AdherentDAO adherentDAO=new AdherentDAO();
        Adherent adherent=new Adherent();
        adherent=adherentDAO.findAdherentByIdSa(reclamation.getAdherentConcerné().getIdAdherent());
        int idAdherent=adherent.getIdAdherent();
        adherentDAO.updateDesactivéCompteAdherentSa(idAdherent);
    }//GEN-LAST:event_bloquerButtonActionPerformed

    private void ReclamationNonTraiteeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReclamationNonTraiteeButtonActionPerformed
        reclamationTable.setModel(new ReclamationsModel(2));
        genererButton.setVisible(true);
        genererButton.setText("Générer rapport");
        //  bloquerButton.setText("Bloquer");
        //bloquerButton.setVisible(true);

        ReclamationNonTraiteeButton.setVisible(false);

        genererButton.setVisible(true);

        /*  RapportTest rapportTest=new  RapportTest();
        try {
            rapportTest.report();
        } catch (JRException ex) {
            Logger.getLogger(Acceuil.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_ReclamationNonTraiteeButtonActionPerformed

    private void genererButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genererButtonActionPerformed
        // TODO add your handling code here:

        int row =reclamationTable.getSelectedRow();
        System.out.println("row  dddddddddddddddddddddddddddddddddddddd"+row);
        int id=(int) reclamationTable.getValueAt(row,0);
        System.out.println("id reclamation"+id);
        Reclamation reclamation=new Reclamation();
        ReclamationDAO reclamationDAO=new ReclamationDAO();
        reclamation=reclamationDAO.findReclamationById(id);
        AdherentDAO adherentDAO=new AdherentDAO();
        Adherent adherent=new Adherent();
        adherent=adherentDAO.findAdherentByIdSa(reclamation.getAdherentConcerné().getIdAdherent());
        if(adherent.getNombreReclamation()>=5)
        {
            System.out.println("bloquer");
            bloquerButton.setText("Bloquer");
            bloquerButton.setVisible(true);
        }

        RapportTest rapportTest=new  RapportTest();
        try {
            rapportTest.report(id);
        } catch (JRException ex) {
            Logger.getLogger(Acceuil.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("ahawa mennaaaa ");
        }
        reclamationDAO.updateReclamationReport(id);

    }//GEN-LAST:event_genererButtonActionPerformed

    private void reclamationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reclamationTableMouseClicked
        // TODO add your handling code here:

        int row =reclamationTable.getSelectedRow();
        String nomReclamateur= (reclamationTable.getModel().getValueAt(row, 1).toString());
        String prenomReclamateur = (reclamationTable.getModel().getValueAt(row, 2).toString());
        String nomAdherentConcerné=(reclamationTable.getModel().getValueAt(row, 3).toString());
        String prenomAdherentConcerné=(reclamationTable.getModel().getValueAt(row, 4).toString());
        String cause=(reclamationTable.getModel().getValueAt(row,5).toString());
        String description=(reclamationTable.getModel().getValueAt(row,6).toString());
        String nombreReclamation=(reclamationTable.getModel().getValueAt(row,7).toString());
        Reclamation reclamation=new Reclamation();

        prenomReclamateurLabel.setText(prenomReclamateur);
        nomReclamateurLabel.setText(nomReclamateur);
        nomAdherentConcernéLabel.setText(nomAdherentConcerné);
        prenomAdherentConcernéLabel.setText(prenomAdherentConcerné);
        causeLabel.setText(cause);
        descriptionTextArea.setText(description);
        nbrReclamationLabel.setText(nombreReclamation);
    }//GEN-LAST:event_reclamationTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReclamationNonTraiteeButton;
    private javax.swing.JButton bloquerButton;
    private javax.swing.JTextField causeLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton genererButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField nbrReclamationLabel;
    private javax.swing.JTextField nomAdherentConcernéLabel;
    private javax.swing.JTextField nomReclamateurLabel;
    private javax.swing.JTextField prenomAdherentConcernéLabel;
    private javax.swing.JTextField prenomReclamateurLabel;
    private javax.swing.JTable reclamationTable;
    // End of variables declaration//GEN-END:variables
}
